version: '3'
services:
  backend:
    container_name: mimic-my-voice-backend
    build:
      context: ./backend/
    ports:
     - "${MRS_PORT_BACKEND}:${MRS_PORT_BACKEND}"
    volumes:
     - ./backend/:/src
    environment:
    - WEBWORKERS=1
  frontend:
    container_name: mimic-my-voice-frontend
    build:
      context: ./frontend/
    ports:
     - "${MRS_PORT_FRONTEND}:${MRS_PORT_FRONTEND}"
    volumes:
     - ./frontend/:/src
